### PR TITLE
fest3

### PR DESCRIPTION
**Pull request by ginkoid**
best fest

### CODE REVIEW

**Comment by dwang** [comment]
I agree with @Arinerron about [the null pointer dereferencing](https://www.youtube.com/watch?v=bLHL75H_VEM). Please fix this as soon as possible.

Thanks!

**Comment by ginkoid** [comment]
sec vulns good

**Comment by Arinerron** [comment]
eh whatever :shipit:  just ship it

**Comment by Arinerron** [comment]
hi i got cve id for this critical vulnerability!! cve-nnn-nnnn

**Comment by Arinerron** [comment]
oh sorry i forgot to fill in template, the numbers are 123 and 1337

**Pull request closed without merging**
